In [1]:
import numpy as np
from scipy import sparse

eye = np.eye(4)
print("Numpy array:\n{}".format(eye))

Numpy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
sparse_matrix = sparse.csr_matrix(eye)
print("\nScipy sparse CSR ma"